_homepage:
    pattern:  /
    defaults: { _controller: GroupPhotoAlbumGeneralBundle:User:index }
    
_user:
    resource: "@GroupPhotoAlbumGeneralBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user
